on: push

jobs:
    back:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@main
        - run: |
              curl https://deb.nodesource.com/setup_current.x | sudo bash -
              sudo apt install -y --no-install-recommends nodejs
              sudo apt purge -y mawk
              PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1 /usr/bin/npm install playwright-chromium
              awk -i inplace /const\ ffmpegExecutable/{sub\(/find.+$/\,\"\'/usr/bin/ffmpeg\'\;\"\)}1 $(/usr/bin/npm root)/playwright-core/lib/server/registry/index.js
              Xvfb :99 &
              DEBUG=pw:api DISPLAY=:99 /usr/bin/node lootably.mjs
        - uses: actions/upload-artifact@main
          with:
              path: |
                  videos
                  screenshot.png
